### PR TITLE
Multiple db

### PR DESCRIPTION
**Pull request by aparzi**
Hi @assuncaocharles,
I added an example of how to use multiple db. I await your feedback, thanks.

### CODE REVIEW

**Comment by assuncaocharles** [comment]
Hey @aparzi 

Why is the `key` being removed from `update`?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
Again for the reason explained in the other issue. The update method fails when updated via key. Due to the way the library is designed, it is not possible to update via key.

**Comment by assuncaocharles** [comment]
@aparzi that makes sense, can you try to get ride of `any` types that are making the pipeline to file?

**Comment by assuncaocharles** [comment]
@all-contributors please add @aparzi  for maintenance

**Comment by aparzi** [comment]
Hi @assuncaocharles, 
i will check any types.

**Comment by aparzi** [comment]
Hi @assuncaocharles,
i can't resolve and check all any types. Could you control them?

**Comment by assuncaocharles** [comment]
@all-contributors please add @aparzi  for code

**Comment by aparzi** [comment]
Hi @assuncaocharles,
Can you check this PR? I don't have much time available at the moment, unfortunately.

**Pull request closed without merging**
