### PR TITLE
Add a method to query non-unique indexes #122

### PR DESCRIPTION
**Pull request by coolweb**

### CODE REVIEW

**Comment by assuncaocharles** [comment]
Hi @coolweb 

Thank you for your contribution.

Can you add on the readme the description and example for the method you created?

**Comment by coolweb** [comment]
> Hi @coolweb
> 
> Thank you for your contribution.
> 
> Can you add on the readme the description and example for the method you created?

Submitted.

**Comment by coolweb** [comment]
@assuncaocharles any news?

**Comment by assuncaocharles** [comment]
@coolweb Thank you, the new version will be published this weekend

**Comment by assuncaocharles** [comment]
@coolweb published

**Pull request merged**
