### PR TITLE
feat: bulk get

### PR DESCRIPTION
**Pull request by aparzi**
Hi @assuncaocharles, 
this pull request feat bulk get operation and refers #244 issue.

### CODE REVIEW

**Comment by aparzi** [comment]
@assuncaocharles let me know if it's ok or you think it's okay to fix something.
Thank you very much.

**Comment by assuncaocharles** [comment]
Hey @aparzi 

Thank you for that, looks pretty much ok I will just run locally and if it's working as expected will merge :)

**Comment by assuncaocharles** [comment]
@aparzi meanwhile you might wanna fix this: https://www.codefactor.io/repository/github/assuncaocharles/ngx-indexed-db/pull/250

**Comment by aparzi** [comment]
@assuncaocharles exactly what's wrong? Because I couldn't figure out if it refers to the whole service

**Pull request merged**
