### PR TITLE
feat: add support multiple DB

### PR DESCRIPTION
**Pull request by aparzi**
With this commit the wrapper allows you to manage multiple DBs for a single URL domain

### CODE REVIEW

**Comment by aparzi** [comment]
@assuncaocharles Any update on these checks and PR progress?

**Comment by aparzi** [comment]
@assuncaocharles I have updated and fixed the previous problems. Thanks

**Comment by aparzi** [comment]
@assuncaocharles Any updates on these checks and on the progress of the PR?  I believe it can be accepted.  These updates concern the issue #230.

Thanks

**Comment by aparzi** [comment]
@assuncaocharles Any update on these checks and PR progress?

**Comment by aparzi** [comment]
@assuncaocharles Any update on these checks and PR progress?

**Comment by aparzi** [comment]
@assuncaocharles Any updates on these checks and on the progress of the PR? I believe it can be accepted. These updates concern the issue #230.

Thanks

**Comment by assuncaocharles** [comment]
Hey @aparzi 

Thanks for the PR, I will have to postpone it for a while yet, I want to set a part some time to test it deeply before merging it.

**Comment by aparzi** [comment]
Hi @assuncaocharles okay, keep me updated. 
Any conflicts how do we manage them?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
are you alright? 

Were you able to test this pull request

**Comment by assuncaocharles** [comment]
Hi @aparzi 

Thank you for pushing this PR and for your patience. I had a chance to look into it, unfortunately this would be a breaking change and I am not sure it is moving in the right directions. I feel like the way Dexie handle multiple databases are better way to go.  So I was wondering alternatives here to avoid having to pass DB configuration details into each method, let's think about how we could achieve something like 

```typescript
export class AppComponent {
    constructor(private personDBService: NgxIndexedDBService('persons', 1), 
        private animalsDBService: NgxIndexedDBService('animals', 1)){
    }
 }
```

or 

```typescript
export class AppComponent {
    animalsDB;
    personsDB;
    constructor(private dbService: NgxIndexedDBService){
         animalsDB = dbService.getDB('animals', 1);
         personsDB = dbService.getDB('persons', 1);
    }
 }
```

or 

```typescript
export class AppComponent {
    constructor(private dbService: NgxIndexedDBService){}
 }

this.dbService
  .useDB('persons', 1)
  .addItem('people', {
    name: `Bruce Wayne`,
    email: `bruce@wayne.com`,
  })
```

In any case we should aim to avoid breaking change here and still support simple 

```typescript
this.dbService
  .addItem('people', {
    name: `Bruce Wayne`,
    email: `bruce@wayne.com`,
  })
```

Let me know what you think

**Comment by aparzi** [comment]
Hi @assuncaocharles thanks for your feedback, I'm fully agree.  

In my opinion the most correct solution would be to inject the generic dbService service and offer a "useDB" method to use another database.  

```​
export​ ​class​ ​AppComponent​ ​{​
    ​animalsDB​;​
    ​personsDB​;​
    ​constructor​(​private​ ​dbService​: ​NgxIndexedDBService​)​{​
         ​animalsDB​ ​=​ ​dbService​.​getDB​(​'animals'​,​ ​1​)​;​
         ​personsDB​ ​=​ ​dbService​.​getDB​(​'persons'​,​ ​1​)​;​
    ​}​
 ​}
```

The first available database is used by default.
In this way we should also maintain backwards compatibility.


 Let me know what you think I proceed with the implementation.  thank you very much :)

**Comment by assuncaocharles** [comment]
I agree, `useDb` as in the following is good solution:

```typescript
export class AppComponent {
    constructor(private dbService: NgxIndexedDBService){}
 }

this.dbService
  .useDB('persons', 1)
  .addItem('people', {
    name: `Bruce Wayne`,
    email: `bruce@wayne.com`,
  })
```

And if not specified using the first or only passed DB

**Comment by aparzi** [comment]
Perfect, when I'm done I will directly update this pull request.

**Pull request closed without merging**
