### PR TITLE
fix(service): fix getById to work with strings

### PR DESCRIPTION
**Pull request by dmlukichev**
`NgxIndexedDBService.getById` method shouldn't transform string key into number.
This causes problems when autoincrement on primary key is disabled (ie: keys are UUIDs).

### CODE REVIEW

**Comment by ziulev** [comment]
Any update here?

**Comment by assuncaocharles** [comment]
Hey, thanks @dmlukichev

Solve the conflicts and I will be able to merge it

**Comment by dmlukichev** [comment]
@assuncaocharles Conflict resolved.

**Comment by dmlukichev** [comment]
@assuncaocharles Can you also publish this version to npm?

**Comment by assuncaocharles** [comment]
@dmlukichev  It's published

**Pull request merged**
