### PR TITLE
feat: #364 - Implement getAllObjectStoreNames

### PR DESCRIPTION
**Pull request by nik-base**
Implementation for #364 - `getAllObjectStoreNames`

### CODE REVIEW

**Comment by aparzi** [comment]
Hi @nik-base,
thanks for this PR. I modify them and they seem ok, I update the libraries and integrate some small changes and publish a new version.

**Comment by aparzi** [comment]
Hi @nik-base,
could you please update the two package.json with version 19.1.0 and realign branch with master, thanks

**Comment by aparzi** [comment]
@nik-base Can you update two package.json with version 19.1.0? Thanks

**Comment by nik-base** [comment]
@aparzi , Yes, sure, I will update the PR.

**Comment by aparzi** [comment]
LGTM

**Pull request merged**
