### PR TITLE
Make lib compatible with ng9

### PR DESCRIPTION
**Pull request by coolweb**
If we do an ng update, this give error because the peer dependencies are ng 8.
This pull request migrates lib to ng 9 and mark it compatible with ng 8 and ng 9.

### CODE REVIEW

**Comment by coolweb** [comment]
Is it ok for you?

**Comment by assuncaocharles** [comment]
Hi @coolweb 

Seems ok for me, can you just check the conflicts?

**Comment by coolweb** [comment]
> Hi @coolweb
> 
> Seems ok for me, can you just check the conflicts?

When I do change, there was no conflict, I see that you just updated now package.json files...

**Comment by coolweb** [comment]
> Hi @coolweb
> 
> Seems ok for me, can you just check the conflicts?

Merge done

**Comment by assuncaocharles** [comment]
Merged. Thanks @coolweb

**Pull request merged**
