### PR TITLE
Angular Universal (SSR) compatibility

### PR DESCRIPTION
**Pull request by ilueckel**
My merge request contains minor changes to allow 
* Import of `NgxIndexedDBModule` without errors running the universal express server
* Small refactoring of `CreateObjectStore` and `openDatabase`.

The problem basically was, that the node server, which serves the Angular Application, tried to access the `window.indexedDB`, which is obviously only available in the browser. So the `NgxIndexedDBService` basically only loads the indexedDB, when we use it in a browser.

Here is some further read: https://github.com/angular/universal/blob/master/docs/gotchas.md

### CODE REVIEW

**Comment by ilueckel** [comment]
I updated the code with the proposed snippet in #156. Also updated the README.md with explanations and sample code.

**Comment by assuncaocharles** [comment]
HI @ilueckel  

I am ready to merge it, but it seem there's some conflicts. Can you check it?

**Comment by ilueckel** [comment]
I merged your upstream changes. Everything should be fine now

**Comment by ilueckel** [comment]
Hi,
do you have any outstanding changes for the next release (on npmjs)? Until the merged changes are released it's kinda holding back my CI.

**Pull request merged**
