### PR TITLE
Add multiple DB capabilities to NgxIndexedDB

### PR DESCRIPTION
**Pull request by sbordeyne**
Issue : #296

This PR allows the NgxIndexedDbService to handle several databases. In order to keep the lib retro compatible, the following syntax is expected, to add multiple databases to a single project :

```ts
import { NgxIndexedDBModule, DBConfig } from 'ngx-indexed-db';

const myDbConfig: DBConfig  = {
  name: 'MyDb',
  version: 1,
  isDefault: true,
  objectStoresMeta: [{
    store: 'people',
    storeConfig: { keyPath: 'id', autoIncrement: true },
    storeSchema: [
      { name: 'name', keypath: 'name', options: { unique: false } },
      { name: 'email', keypath: 'email', options: { unique: false } }
    ]
  }]
};

const myOtherDbConfig: DBConfig  = {
  name: 'MyOtherDb',
  version: 1,
  objectStoresMeta: [{
    store: 'people',
    storeConfig: { keyPath: 'id', autoIncrement: true },
    storeSchema: [
      { name: 'name', keypath: 'name', options: { unique: false } },
      { name: 'email', keypath: 'email', options: { unique: false } }
    ]
  }]
};

@NgModule({
  ...
  imports: [
    ...
    NgxIndexedDBModule.forRoot(myDbConfig, myOtherDbConfig)
  ],
  ...
})
```

In order to keep it compatible with previous code, specifying the database name to do operations on is optional. A default DB can be declared, otherwise an error will be thrown. If only one DB is configured, this is assumed to be the default db.

If no database name is specified, and no default DB is set, the code will throw an error.

### CODE REVIEW

**Comment by sbordeyne** [comment]
@assuncaocharles Have you had the time to take a look at my PR ?

**Comment by assuncaocharles** [comment]
> @assuncaocharles Have you had the time to take a look at my PR ?

Going to look today. @aparzi if you want have some 👁️  here also

**Comment by aparzi** [comment]
Hi @assuncaocharles,
I could see it Monday.

**Comment by sbordeyne** [comment]
@aparzi @assuncaocharles Have you had the time to look it over and review my pull request ? Thank you

**Comment by aparzi** [comment]
Hi @Dogeek,

I took a quick look and everything seems to be ok. The only thing that bothers me is the length of the method signature, in some cases reaches 4 input parameters, it would be preferable not to exceed 3 parameters.

**Comment by sbordeyne** [comment]
I did it this way to not cause problems when migrating existing code to a new version, reducing the number of parameters would require a change in all of the method signatures to use object unpacking instead.

If that's the route to take, I'll be more than happy to do the change, but that will cause a major version bump of the library

**Comment by aparzi** [comment]
Yes I understood. let's wait what @assuncaocharles  thinks too

**Comment by sbordeyne** [comment]
@aparzi I just thought of another option, which would be to add a `selectDb` method, that way most of the code would remain the same as it was previously, and database selection would have to be done after the service is injected.

Let me know what you think

**Comment by aparzi** [comment]
Hi @Dogeek,
In this way, by injecting the service, a component can still interact with multiple databases at runtime?

**Comment by ghost** [comment]
> Hi @Dogeek,
> In this way, by injecting the service, a component can still interact with multiple databases at runtime?

Yes, but you may have to call selectDb several times.

**Comment by aparzi** [comment]
Sure. I think it's better, that's okay

**Comment by aparzi** [comment]
@assuncaocharles what do you think?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
any news for this PR ?

**Comment by sbordeyne** [comment]
@assuncaocharles Hello, I'd really like for this to be merged ASAP if it's not too much trouble with you. I kinda need this feature at work 😄

**Comment by assuncaocharles** [comment]
Sorry for the delay and thanks for the PR @Dogeek

**Pull request merged**
