### PR TITLE
Integration SSR 

### PR DESCRIPTION
**Pull request by MRinaldi9**
This PR integrate a new logic for handling SSR code in Angular, without "forking" logic in service.

### CODE REVIEW

**Comment by aparzi** [comment]
Hi @MRinaldi9,
awesome PR. Can you fix CodeFactor issues? Please, also update two package at 19.2.0 and if you want to update the readme to inform users that the library supports SSR

**Comment by MRinaldi9** [comment]
Hi @aparzi,
I can try to fix as many CodeFactor issues as possible, but the requested fixes are related to variables that are not utilized in the server-side implementation of IndexedDB and there is no use for them on the server side, so i don't know if there is a way to inform CodeFactor to avoid the check or use a stratagem for trick CodeFactor.
For the two packages do you intend the library and workspace?
In which section of the Readme do you think is better to add the information about SSR?

**Comment by aparzi** [comment]
@MRinaldi9 for CodeFactor I can inspect, for this point do as you prefer. 

- Yes, package.json in library and workspace. New version 19.1.1

- I think it's to include on the top description before install chapter. I'm also open also a new ideas.

Many thanks.

**Comment by MRinaldi9** [comment]
As per your request, @aparzi, I have updated the version in `package.json`, added new sections to the README (including specific integrations), and resolved some of the issues raised by CodeFactor.

**Comment by aparzi** [comment]
Awesome PR  🔥🔥
Can you just update the branch to the latest changes in master? I closed a small issue now.

Thanks

**Comment by MRinaldi9** [comment]
Updated PR with branch `master`

**Pull request merged**
