### PR TITLE
Fix issue 297

### PR DESCRIPTION
**Pull request by aparzi**
Hi @assuncaocharles,
fix the problem related to issue number #297. As it is designed, the indexeddb wrapper allows you to create stores with only in-line keys. For this reason, calling the put (native) method specifying the key, a Dom Exception is thrown.
I also report documentation on:
https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/put#exceptions

### CODE REVIEW

**Comment by aparzi** [comment]
Hi @assuncaocharles,
any news for this PR?

**Comment by assuncaocharles** [comment]
Hey @aparzi 

Thanks for the PR, I am not sure if we should remove the `key` from update since in the Issue reported seems like using `update` works as expected?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
for the update method the key is optional, you have to understand if this is passed as a parameter. Because in the tests I performed if the key is passed, the update method also fails for the same reason (above)

**Comment by aparzi** [comment]
Hi @assuncaocharles,
Were you able to get the update or update by key method to work by passing it the key? For the above documentation, it is not possible to update an entity by key

**Comment by aparzi** [comment]
Hi @assuncaocharles,
any news for this issue? Thanks

**Comment by assuncaocharles** [comment]
Sorry for the long delay, crazy days here. I managed to test it, sounds fine I will release it as a major version tho since we are breaking our own API.

**Pull request merged**
